name: absence_manager_app
description: Absence Manager
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^9.0.0
  bloc_concurrency: ^0.3.0
  chopper: ^8.1.0
  connectivity_plus: ^6.1.3
  dartz: ^0.10.1
  data_table_2:  2.5.15
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.3
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logging: ^1.3.0
  responsive_framework: ^1.5.1


dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.13
  chopper_generator: ^8.0.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
